#!/usr/bin/env node
import{fileURLToPath as __fup}from'url';import{dirname as __dn}from'path';import{createRequire as __cr}from'module';const __filename=__fup(import.meta.url);const __dirname=__dn(__filename);const require=__cr(import.meta.url);
import{exec as v}from"child_process";import*as y from"http";import*as T from"readline";import*as i from"fs";import*as E from"os";import*as d from"path";var m={name:"wozcode",version:"0.2.0",description:"WozCode enhanced coding tools \u2014 smart search, batch editing, SQL introspection, and cost-optimized subagent delegation",homepage:"https://withwoz.com",type:"module",main:"dist/standalone/cli.js",bin:{wozcode:"./dist/standalone/cli.js"},scripts:{build:"tsc && chmod +x dist/standalone/cli.js","build:plugin":"tsc && node dist/plugin/build-plugin.js",dev:"tsx src/standalone/cli.ts",start:"node dist/standalone/cli.js",lint:"npx eslint src/",compile:"tsc --noEmit",format:"npx prettier --write 'src/**/*.{ts,js}'"},author:"Woz",license:"UNLICENSED",dependencies:{"@anthropic-ai/claude-agent-sdk":"~0.2.74","@anthropic-ai/sdk":"~0.78.0","@modelcontextprotocol/sdk":"^1.27.1","@pg-nano/pg-parser":"~16.1.5",commander:"~14.0.3",glob:"^13.0.6",postgres:"~3.4.7",typescript:"~5.9.2",yaml:"^2.8.3",zod:"^4.3.6"},devDependencies:{"@eslint/js":"~10.0.1","@types/node":"~25.5.0","@typescript-eslint/utils":"^8.57.2",esbuild:"^0.27.4",eslint:"~10.1.0",tsx:"~4.21.0","typescript-eslint":"^8.57.2"},engines:{node:">=20.10"}};var M="woz",X=`/${M}:login`,Y=m.version,O=".wozcode",h="config.json",C="auth.json";function f(){return d.join(E.homedir(),O)}function S(){return d.join(f(),h)}function _(){return d.join(f(),C)}function A(){let e=f();i.existsSync(e)||i.mkdirSync(e,{recursive:!0})}function l(){let e=S();try{let o=i.readFileSync(e,"utf8");return JSON.parse(o)}catch{return{}}}function x(e){A();let o=S();i.writeFileSync(o,JSON.stringify(e,null,2),"utf8")}function I(){let e=_();try{let o=i.readFileSync(e,"utf8");return JSON.parse(o)}catch{return}}function g(e){A();let o=_();i.writeFileSync(o,JSON.stringify(e,null,2),{encoding:"utf8",mode:384})}function N(){let e=_();try{i.unlinkSync(e)}catch{}}var L="https://builder.withwoz.com",z="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",W="https://build.withwoz.com";function p(){let e=l();return{supabaseUrl:process.env.WOZCODE_SUPABASE_URL??e.supabaseUrl??L,supabaseAnonKey:process.env.WOZCODE_SUPABASE_ANON_KEY??e.supabaseAnonKey??z,appUrl:process.env.WOZCODE_APP_URL??e.appUrl??W}}var te=["WOZ","INTERNAL","KEY"].join("_");var se=1800*1e3;var R=600*1e3,j=60*1e3,P=process.stdin.isTTY??!1;async function b(e){if(e!=null)return G(e);let o=p(),t=49152+Math.floor(Math.random()*16384);console.log(`Starting WozCode authentication...
`);let{promise:n,shutdown:r}=F(t),a=`${o.appUrl}/wozcode/auth?callback_port=${t}`;console.log(`Opening browser to: ${a}
`),H(a);let s=[n];P?(console.log("Waiting for browser callback..."),console.log(`Or paste your token below (from the token page in your browser):
`),s.push(J()),s.push(w(R))):(console.log(`Waiting for browser callback...
`),s.push(w(j)));let c=await Promise.race(s);if(r(),c!=null)return g(c),console.log(`
Authenticated as ${c.email}`),c;console.error(P?`
Authentication timed out.`:`
Authentication timed out. The browser callback did not receive a response.`)}async function k(){N(),console.log("Logged out of WozCode.")}async function D(){return I()}function F(e){let o,t=new Promise(r=>{o=y.createServer((a,s)=>{if(s.setHeader("Access-Control-Allow-Origin","*"),s.setHeader("Access-Control-Allow-Methods","POST, OPTIONS"),s.setHeader("Access-Control-Allow-Headers","Content-Type"),a.method==="OPTIONS"){s.writeHead(204),s.end();return}if(a.method==="POST"&&a.url==="/callback"){let c="";a.on("data",u=>{c+=u.toString()}),a.on("end",()=>{try{let u=JSON.parse(c);s.writeHead(200,{"Content-Type":"application/json"}),s.end(JSON.stringify({ok:!0})),r(u)}catch{s.writeHead(400),s.end("Invalid JSON")}});return}s.writeHead(404),s.end()}),o.listen(e,"127.0.0.1")});function n(){o?.close()}return{promise:t,shutdown:n}}function J(){return new Promise(e=>{let o=T.createInterface({input:process.stdin}),t="";o.on("line",n=>{t+=n;try{let r=JSON.parse(t.trim());if(r.accessToken&&r.refreshToken){o.close(),e(r);return}}catch{}}),o.on("close",()=>{if(t.trim())try{let n=JSON.parse(t.trim());if(n.accessToken&&n.refreshToken){e(n);return}}catch{}e(void 0)})})}function w(e){return new Promise(o=>{setTimeout(()=>o(void 0),e)})}function Z(e){if(typeof e!="object"||e==null)return!1;let o=e;return typeof o.accessToken=="string"&&typeof o.refreshToken=="string"&&typeof o.expiresAt=="string"&&typeof o.userId=="string"&&typeof o.email=="string"}function G(e){try{let o=JSON.parse(e);if(!Z(o)){console.error("Invalid token JSON: missing required fields."),console.error("Required fields: accessToken, refreshToken, expiresAt, userId, email");return}return g(o),console.log(`
Authenticated as ${o.email}`),o}catch(o){console.error(`Failed to parse token JSON: ${o instanceof Error?o.message:String(o)}`);return}}function H(e){let o=process.platform==="darwin"?`open "${e}"`:process.platform==="win32"?`start "" "${e}"`:`xdg-open "${e}"`;v(o,t=>{t&&console.log(`Could not open browser. Visit this URL manually:
  ${e}
`)})}import{spawn as $}from"child_process";var B=process.argv[2];switch(B){case"login":{let e=process.argv.indexOf("--token"),o=e!==-1?process.argv[e+1]:void 0,t=await b(o);if(t!=null){let n=p(),r=l();r.supabaseUrl=n.supabaseUrl,r.supabaseAnonKey=n.supabaseAnonKey,r.appUrl=n.appUrl,x(r),console.log(`
Config saved to ~/.wozcode/config.json`)}process.exit(t!=null?0:1);break}case"logout":{await k(),process.exit(0);break}case"status":{let e=await D();if(e==null)console.log("Not logged in. Run `wozcode login` to authenticate.");else{let o=new Date(e.expiresAt),t=o<new Date;console.log(`Logged in as: ${e.email}`),console.log(`User ID:      ${e.userId}`),console.log(`Token expires: ${o.toLocaleString()}${t?" (EXPIRED)":""}`);let n=l();n.supabaseUrl&&console.log(`Supabase:     ${n.supabaseUrl}`),n.appUrl&&console.log(`App URL:      ${n.appUrl}`)}process.exit(0);break}default:{$("claude",["--agent","wozcode",...process.argv.slice(2)],{stdio:"inherit"}).on("exit",o=>process.exit(o??0));break}}
